### ISSUE TITLE
大佬们能不能来个小白教程

### ISSUE THREAD

**Issue by kyerbas** [EssayKillerBrain/EssayKiller_V2#23]
大佬们能不能来个小白教程啊，按着clab的代码，下载谷歌的3个文件到本地，部署完各种报错

FileNotFoundError: [Errno 2] No such file or directory: 'result.txt'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by kyerbas** [comment]
(aitext) laogege@localhost GPT2 % python scripts/demo.py -ckpt_fn finetune/trained_models/model.ckpt-280000 -min_len 150 -samples 5
python scripts/formatter.py -org_text result.txt
我的老师WARNING:tensorflow:From /Users/laogege/pythonwork3/aitext/EssayKiller_V2-master/LanguageNetwork/GPT2/scripts/modeling.py:141: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py:180: batch_gather (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2017-10-25.
Instructions for updating:
`tf.batch_gather` is deprecated, please use `tf.gather` with `batch_dims=-1` instead.
Traceback (most recent call last):
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: finetune/trained_models/model.ckpt-280000.data-00000-of-00001; No such file or directory
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: finetune/trained_models/model.ckpt-280000.data-00000-of-00001; No such file or directory
	 [[node save/RestoreV2 (defined at /Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "scripts/demo.py", line 178, in <module>
    saver = tf.compat.v1.train.Saver()
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/demo.py", line 179, in <module>
    saver.restore(sess, args.ckpt_fn)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

finetune/trained_models/model.ckpt-280000.data-00000-of-00001; No such file or directory
	 [[node save/RestoreV2 (defined at /Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "scripts/demo.py", line 178, in <module>
    saver = tf.compat.v1.train.Saver()
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/Users/laogege/.pyenv/versions/aitext/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

(aitext) laogege@localhost GPT2 % python scripts/formatter.py -org_text result.txt
the lens:  13
Traceback (most recent call last):
  File "scripts/formatter.py", line 132, in <module>
    with open(args.org_text, 'r',encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'result.txt'

**Comment by qiluwanbao** [comment]
你是怎么搞定的啊？

**Comment by ShiGl97** [comment]
+1
